// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlnwvuaidgbbtqvuwocp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbnd2dWFpZGdiYnRxdnV3b2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTAwMjAsImV4cCI6MjA2MzIyNjAyMH0.nnvEaBQTaoh2afLERD3D3BMHDwaoE_vfFc92BFJ0F5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);